### ISSUE TITLE
Fails in CircleCI

### ISSUE THREAD

**Issue by kyeotic** [rogeriochaves/npm-force-resolutions#11]
This works locally, but errors with the following in CircleCI

```
#!/bin/bash -eo pipefail
npm install
npm WARN lifecycle dev-portal@3.0.0~preinstall: cannot run in wd dev-portal@3.0.0 npx npm-force-resolutions (wd=/tmp/app)
```

**Comment by lazar-vuckovic** [comment]
Please take a look at [my comment from another issue](https://github.com/rogeriochaves/npm-force-resolutions/issues/10#issuecomment-601951821) on how I managed to resolve it with a dirty workaround.

**Comment by ronaldbarendse** [comment]
This doesn't work, because you should be using `npm ci` with an already patched `package-lock.json`: https://docs.npmjs.com/cli/ci.html
