### ISSUE TITLE
cant install webpack 5 in angular 

### ISSUE THREAD

**Issue by Julian-B90** [rogeriochaves/npm-force-resolutions#20]
We want to test Angular 11 with webpack 5. 

But wenn we to the install with the preinstall webpack was remove from `node_modules`.

**Comment by superole** [comment]
Interesting. That was the exact reason why I was checking out this tool today too. So that probably means I have to take a different approach then... Did you find another solution @Julian-B90 ?

**Comment by Julian-B90** [comment]
Not yet sorry. As workaroung i use yarn.

**Comment by rogeriochaves** [comment]
sorry, this tool was built 3 years ago, I think npm changed how they read lockfile since then so it no longer works properly, I haven't had the time to update it anymore
