### ISSUE TITLE
version 0.0.4 cannot find module error

### ISSUE THREAD

**Issue by gamalielhere** [rogeriochaves/npm-force-resolutions#22]
this was working before the new version. Now I'm getting this error:

`Cannot find module '/Users/user/.npm/_cacache/_npx/4714/lib/node_modules/npm-force-resolutions/.cljs_node_repl/goog/bootstrap/nodejs.js'`

**Comment by kvhnuke** [comment]
`npx npm-force-resolutions` will cause that error

**Comment by gamalielhere** [comment]
`npx npm-force-resolutions@0.03 currently resolves this issue`

**Comment by ericgrainbridge** [comment]
I'm seeing this issue too. I hope there's a solution soon. I don't want to have to change the version in all of our microservices.

**Comment by hems** [comment]
same error here

**Comment by Falco101** [comment]
Erroring out here as well. Forcing v0.0.3 works for now.

**Comment by wmhartl** [comment]
Same here.

**Comment by brendonottofmg** [comment]
Same here

**Comment by mccannm11** [comment]
Same.

**Comment by lindsaykulz** [comment]
Same

**Comment by createthis** [comment]
same

**Comment by davidsiu** [comment]
Getting this same error because of this work around https://github.com/parcel-bundler/parcel/issues/5145 . I'm pinned to 0.0.3 but some how still getting this error.

**Comment by MuckT** [comment]
Same error here, forcing v0.0.3 works for now; Thanks @gamalielhere.

`"preinstall": "npx npm-force-resolutions@0.0.3"`

**Comment by dman777** [comment]
same here

**Comment by andynunes** [comment]
Boy, did I think I was dumb for a second.

**Comment by nalham** [comment]
I've submitted a potential fix for this https://github.com/rogeriochaves/npm-force-resolutions/pull/24

**Comment by phugodness** [comment]
same :(

**Comment by rogeriochaves** [comment]
sorry folks, I didn't test it properly the published version, thanks to @nalham, I've merged #24 and published again, should be fixed on 0.0.5, but let me know of any issues

**Comment by nalham** [comment]
thanks @rogeriochaves !
