### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by g-bastianelli** [rogeriochaves/npm-force-resolutions#28]
Hello. Its what i havsince your release.
```shell
 npx npm-force-resolutions

Need to install the following packages:
  npm-force-resolutions
Ok to proceed? (y) y
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null
    at Function.from (buffer.js:333:9)
    at /Users/g-bastianelli/Projects/kronos/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:26:36
    at npm_force_resolutions$core$build_dependency_from_dist (/Users/g-bastianelli/Projects/kronos/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:30:3)
    at switch__2144__auto__ (/Users/g-bastianelli/Projects/kronos/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:32:3)
    at /Users/g-bastianelli/Projects/kronos/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:32:3
    at npm_force_resolutions$core$fetch_resolved_resolution_$_state_machine__2145__auto____1 (/Users/g-bastianelli/Projects/kronos/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:95:4)
    at cljs.core.async.impl.ioc-helpers/FN-IDX (/Users/g-bastianelli/Projects/kronos/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:111:94)
    at cljs.core.async.impl.ioc-helpers/run-state-machine (/Users/g-bastianelli/Projects/kronos/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
    at cljs.core.async.impl.ioc-helpers/run-state-machine-wrapped (/Users/g-bastianelli/Projects/kronos/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:39:6)
    at /Users/g-bastianelli/Projects/kronos/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:48:39
```

it's happening on my CI too. Node14 and npm 7

**Comment by ihtisham-sohail** [comment]
Same here, using Node v12.16.1 , NPM v6.13.4 , even i didn't do anything recently with my App.

**Comment by irfanbabar15** [comment]
same here, suddenly my github eslint giving me this issue on PR, i tried npm install in my local code. Then I get this same issue in local as well.

**Comment by CookieBox** [comment]
We were able to resolve the issue by updating all of the items in "resolutions" within our packages.json. For us, we updated to the following and the problem went away. Can't specify this is a correct or valid fix, but it has resolved the issue for us :) 

**Original:**
"resolutions": {
    "https-proxy-agent": "2.2.4", 
    "node-sass": "^4.13.1",
    "serialize-javascript": "^2.1.1",
    "tree-kill": "1.2.2"
  }

**Updated:**
"resolutions": {
    "https-proxy-agent": "5.0.0", 
    "node-sass": "5.0.0",
    "serialize-javascript": "5.0.1",
    "tree-kill": "1.2.2"
  }

I hope this helps!

**Comment by g-bastianelli** [comment]
[![Image from Gyazo](https://i.gyazo.com/df8eb10f5eed41ae2d33d6d38f44bfe1.gif)](https://gyazo.com/df8eb10f5eed41ae2d33d6d38f44bfe1)

remove the `^` of the resolutions was the fix for me.

**Comment by fabio-510** [comment]
Same happened here since the latest version was published. Thanks for sharing the workaround

**Comment by fschulze** [comment]
One can also use ``"npx npm-force-resolutions@0.0.6"`` to pin the used version in the ``"scripts"`` -> ``"preinstall"`` part.

**Comment by g-bastianelli** [comment]
> One can also use `"npx npm-force-resolutions@0.0.6"` to pin the used version in the `"scripts"` -> `"preinstall"` part.

Wasn't working for me

**Comment by irfanbabar15** [comment]
> 
> 
> [![Image from Gyazo](https://camo.githubusercontent.com/59082f2ab2ab2259a66ccfe6abacb72e93f1d9008bc371a8bd2efda0631891cd/68747470733a2f2f692e6779617a6f2e636f6d2f64663865623130663565656434316165326433336436643338663434626665312e676966)](https://gyazo.com/df8eb10f5eed41ae2d33d6d38f44bfe1)
> 
> remove the `^` of the resolutions was the fix for me.

IT Worked for me Thanks. But why ^ sign isn't working for resolution. any idea ?

**Comment by g-bastianelli** [comment]
I think that it's a matter of type. When we use ^ version handle as an object i guess and without as a string.

**Comment by vfreitas-** [comment]
I think it's an issue with the latest version (0.0.7). In my project, I did a downgrade and it worked nicely.
```
"preinstall": "npx npm-force-resolutions@0.0.6"
```

**Comment by pagniezg** [comment]
looks like its related with this commit : https://github.com/rogeriochaves/npm-force-resolutions/commit/986fb7c7068d963963b80cbdc046dbecf9669e42

my guessing : function is looking to the integrity hash in the dependencies. On some dependencies (had the problem with graceful-fs), this hash is empty and the method couldn't find sha-1 or base64 hash : crash.

**Comment by jcardali** [comment]
> I think it's an issue with the latest version (0.0.7). In my project, I did a downgrade and it worked nicely.
> 
> ```
> "preinstall": "npx npm-force-resolutions@0.0.6"
> ```

I will be doing this going forward after multiple issues this week.

**Comment by mredaelli** [comment]
> One can also use `"npx npm-force-resolutions@0.0.6"` to pin the used version in the `"scripts"` -> `"preinstall"` part.

Don't you love pinning the version of the version-pinner ^_^

**Comment by createthis** [comment]
You broke it AGAIN in the same week. lol. You guys need a better QA procedure.

**Comment by danizep** [comment]
Thank you! 😄 
This bug triggered an improvement in our code by stop using `npm-force-resolutions` and fixing the actual problem! 😉

**Comment by rogeriochaves** [comment]
well, what can I say, sorry
to be honest folks, I didn't even knew that ^ versions were supported, because I never really used like that, that's why I don't have a unit test for it, it was working by accident so far

turns out npm is quite a complicated thing, when trying to fix other issues where integrity was not fetched properly, I end up breaking this one, because npm api does not support urls like `https://registry.npmjs.org/hoek/^4.2.1`, so I reversed to the old behaviour of not having integrity checks if version has ^ in it

should be fixed by 5734f5c98f37d9e55f6c1a74b17f2faece8724bc, and now released on `v0.0.9`, please let me know of any further issues

@danizep that's a great outcome! 😃

**Comment by kalbert312** [comment]
`~` doesn't seem to work. I stopped using `^` in favor of `~` in the rare event a `package-lock.json` needs to be regenerated as patch variations have less chance to break things.

**Comment by rogeriochaves** [comment]
@kalbert312 I will follow up on #29

**Comment by fabio-s-franco** [comment]
@rogeriochaves don't beat yourself up. Your work is saving us a lot of trouble and I am thankful for that. It's great the the community quickly found a workaround to this small hiccup and now there there is test coverage.

Keep up the good work :)
