### ISSUE TITLE
in npm 6, npm install undoes resolutions

### ISSUE THREAD

**Issue by BryanCrotaz** [rogeriochaves/npm-force-resolutions#3]
`npm i` undoes the good work of npm-force-resolutions

**Comment by nathanbirrell** [comment]
Yarn it is

**Comment by rogeriochaves** [comment]
Fixed for npm 6 on PR #7, unfortunatelly instructions changed, now you need to add this to your scripts on package.json:

```json
"preinstall": "npx npm-force-resolutions"
```

Because npm keeps fixing it we need to fix it back

Cheers!
