### ISSUE TITLE
npm preinstall fails but not when I run npx npm-force-resolutions 

### ISSUE THREAD

**Issue by tommyc38** [rogeriochaves/npm-force-resolutions#44]
My package.json looks like this:
```
...
scripts: {
    "preinstall": "npx npm-force-resolutions"
     ...
}
...
```
When I run `npm install` or `npm run preinstall` I get an auth error.  The odd thing is that if I run 'npx npm-force-resolutions" runs fine OR if I remove the preinstall script from package.json, `npm install` runs without issue.  Any idea what would cause this?

Error:
```
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="MyGet - <private name here>"

npm ERR! A complete log of this run can be found in:

```
I don't have an `.npmrc` in my home folder and have my `.npmrc` setup correctly with a token since it's pulling down private packages from a private registry.  I'm at a loss here.

**Comment by tommyc38** [comment]
I added the .npmrc file in the project to my home directory, which didn't have one, and it runs fine now.  I thought npm was supposed to look up the project .npmrc file before going to the home directory???

**Comment by Donhv** [comment]
> roject .np

thanks. i dont understand why we need to do it.
